Repository JohnSnowLabs/nlu, pull requests merged in 2020-10, with the labels that each got.

#12 1.0.1rc1
  docs/en/install.md
  nlu/components/spell_checkers/norvig_spell/component_infos.json
  nlu/pipeline.py
  setup.py
  tests/nlu_core_tests/component_tests/classifier_tests/e2e_tests.py
  tests/nlu_core_tests/component_tests/classifier_tests/language_tests.py
  tests/nlu_core_tests/component_tests/classifier_tests/ner_tests.py
  tests/nlu_core_tests/component_tests/classifier_tests/pos_tests.py
  tests/nlu_core_tests/component_tests/classifier_tests/question_tests.py
Labels: bug, enhancement

#13 Lev updates
  docs/_includes/article-footer.html
  docs/_includes/article-header.html
  docs/_includes/article-section-navigator.html
  docs/_includes/article/footer/license.html
  docs/_includes/article/footer/subscribe.html
  docs/_includes/footer.html
  docs/_includes/header.html
  docs/_includes/scripts/custom.js
  docs/_layouts/docs.html
  docs/_layouts/landing.html
  docs/_layouts/page.html
  docs/_sass/custom.scss
  docs/assets/images/main-bg1.jpg
  docs/en/NLU_under_the_hood.md
  docs/en/concepts.md
  docs/en/examples.md
  docs/en/install.md
  docs/en/load_api.md
  docs/en/model_namespace.md
  docs/en/notebooks.md
  docs/en/predict_api.md
  docs/en/release_notes.md
  docs/en/viz_examples.md
  docs/old_index.md
Labels: documentation, enhancement

#8 Relax the pyspark/spark-nlp dependencies
  setup.py
Labels: enhancement
