Repository JohnSnowLabs/nlu, pull requests merged in 2022-04, with the labels that each got.

#108 gemfile updated
  docs/Gemfile.lock
Labels: documentation, duplicate

#109 gemfile updated
  docs/Gemfile.lock
Labels: documentation

#110 Detection and fix of NLP-Internal version missmatch with secrets
  nlu/utils/environment/authentication.py
  tests/nlu_hc_tests/verification_tests.py
Labels: enhancement

#113 Improved nlu component access
  nlu/__init__.py
  nlu/pipe/component_resolution.py
  nlu/pipe/nlu_component.py
  nlu/pipe/pipe_logic.py
  nlu/pipe/pipeline.py
  nlu/pipe/utils/pipe_utils.py
  nlu/pipe/utils/resolution/nlu_ref_utils.py
  nlu/pipe/viz/streamlit_viz/viz_building_blocks/block_utils/entity_manifold_utils.py
  nlu/spellbook.py
  nlu/universe/annotator_class_universe.py
  nlu/universe/component_universes.py
  nlu/universe/feature_resolutions.py
  nlu/universe/feature_universes.py
  nlu/utils/environment/offline_load_utils.py
Labels: refactor

#115 BUGFIX: update ruby github pages
  docs/Gemfile
  docs/Gemfile.lock
Labels: refactor
