Repository JohnSnowLabs/nlu, pull requests merged in 2022-07, with the labels that each got.

#124 Integration of chunk mapper Annotator and 17 new Models and 10 new pipes
  nlu/components/chunkers/chunk_mapper/__init__.py
  nlu/components/chunkers/chunk_mapper/chunk_mapper.py
  nlu/components/chunkers/chunk_mapper/component_infos.json
  nlu/pipe/col_substitution/col_substitution_HC.py
  nlu/pipe/col_substitution/name_deduction/name_deductable_annotators_HC.py
  nlu/pipe/col_substitution/substitution_map_HC.py
  nlu/pipe/extractors/extractor_configs_HC.py
  nlu/pipe/extractors/extractor_methods/base_extractor_methods.py
  nlu/pipe/extractors/extractor_methods/helper_extractor_methods.py
  nlu/pipe/pipe_logic.py
  nlu/pipe/pipeline.py
  nlu/pipe/utils/pipe_utils.py
  nlu/pipe/utils/predict_helper.py
  nlu/spellbook.py
  nlu/universe/annotator_class_universe.py
  nlu/universe/component_universes.py
  nlu/universe/feature_node_ids.py
  nlu/universe/feature_node_universes.py
  nlu/universe/feature_universes.py
  nlu/universe/logic_universes.py
  tests/nlu_hc_tests/component_tests/chunkmapper/__init__.py
  tests/nlu_hc_tests/component_tests/chunkmapper/chunk_mapper_tests.py
Labels: enhancement

#127 Feature/span classifiers from Spark NLP 4.0 962 models
  nlu/components/classifiers/span_albert/__init__.py
  nlu/components/classifiers/span_albert/component_infos.json
  nlu/components/classifiers/span_albert/span_albert.py
  nlu/components/classifiers/span_bert/__init__.py
  nlu/components/classifiers/span_bert/component_infos.json
  nlu/components/classifiers/span_bert/span_bert.py
  nlu/components/classifiers/span_deberta/__init__.py
  nlu/components/classifiers/span_deberta/component_infos.json
  nlu/components/classifiers/span_deberta/span_deberta.py
  nlu/components/classifiers/span_distilbert/__init__.py
  nlu/components/classifiers/span_distilbert/component_infos.json
  nlu/components/classifiers/span_distilbert/span_distilbert.py
  nlu/components/classifiers/span_longformer/__init__.py
  nlu/components/classifiers/span_longformer/component_infos.json
  nlu/components/classifiers/span_longformer/span_longformer.py
  nlu/components/classifiers/span_roberta/__init__.py
  nlu/components/classifiers/span_roberta/component_infos.json
  nlu/components/classifiers/span_roberta/span_roberta.py
  nlu/components/classifiers/span_xlm_roberta/__init__.py
  nlu/components/classifiers/span_xlm_roberta/component_infos.json
  nlu/components/classifiers/span_xlm_roberta/span_xlm_roberta.py
  nlu/components/utils/README.md
  nlu/components/utils/multi_document_assembler/__init__.py
  nlu/components/utils/multi_document_assembler/component_infos.json
  nlu/components/utils/multi_document_assembler/spark_nlp_multi_document_assembler.py
  nlu/finance.py
  nlu/ocr_components/pdf_builders/__init__.py
  nlu/ocr_components/pdf_builders/text2pdf/__init__.py
  nlu/ocr_components/visual_classifiers/__init__.py
  nlu/ocr_components/visual_classifiers/visual_doc_classifier/__init__.py
  nlu/pipe/col_substitution/col_name_substitution_utils.py
  nlu/pipe/col_substitution/col_substitution_OS.py
  nlu/pipe/col_substitution/name_deduction/name_deductable_annotators_OS.py
  nlu/pipe/col_substitution/substitution_map_HC.py
  nlu/pipe/component_resolution.py
  nlu/pipe/extractors/extractor_configs_OS.py
  nlu/pipe/extractors/extractor_methods/base_extractor_methods.py
  nlu/pipe/pipe_logic.py
  nlu/pipe/pipeline.py
  nlu/pipe/utils/component_utils.py
  nlu/pipe/utils/data_conversion_utils.py
  nlu/pipe/utils/pipe_utils.py
  nlu/pipe/utils/predict_helper.py
  nlu/spellbook.py
  nlu/universe/annotator_class_universe.py
  nlu/universe/component_universes.py
  nlu/universe/feature_node_ids.py
  nlu/universe/feature_node_universes.py
  nlu/universe/feature_resolutions.py
  nlu/universe/feature_universes.py
  nlu/universe/logic_universes.py
  tests/release_tests/release_400/__init__.py
  tests/release_tests/release_400/span_question_data_conversion_tests.py
  tests/release_tests/release_400/tests_400.py
Labels: enhancement

#126 added healthcare 4.0 models
  docs/Gemfile.lock
  nlu/spellbook.py
  tests/release_tests/release_400/tests_400.py
Labels: enhancement

#128 Feature/span bert coref model integration
  nlu/components/coref/__init__.py
  nlu/components/coref/coref_bert/__init__.py
  nlu/components/coref/coref_bert/component_infos.json
  nlu/components/coref/coref_bert/coref_bert.py
  nlu/pipe/col_substitution/col_substitution_OS.py
  nlu/pipe/extractors/extractor_base_data_classes.py
  nlu/pipe/extractors/extractor_configs_OS.py
  nlu/pipe/extractors/extractor_methods/base_extractor_methods.py
  nlu/pipe/extractors/extractor_methods/helper_extractor_methods.py
  nlu/pipe/pipeline.py
  nlu/pipe/utils/pipe_utils.py
  nlu/spellbook.py
  nlu/universe/annotator_class_universe.py
  nlu/universe/component_universes.py
  nlu/universe/feature_node_ids.py
  nlu/universe/feature_node_universes.py
  nlu/universe/feature_universes.py
  nlu/universe/logic_universes.py
  tests/nlu_core_tests/component_tests/span_bert_coref_tests/__init__.py
  tests/nlu_core_tests/component_tests/span_bert_coref_tests/span_bert_coref.py
Labels: enhancement

#129 4.0.0 tests
  tests/nlu_core_tests/component_tests/span_classifier_tests/albert_for_question_answering _tests.py
  tests/nlu_core_tests/component_tests/span_classifier_tests/bert_for_question_answering.py
  tests/nlu_core_tests/component_tests/span_classifier_tests/deberta_for_question_answering.py
  tests/nlu_core_tests/component_tests/span_classifier_tests/distilbert_for_question_answering.py
  tests/nlu_core_tests/component_tests/span_classifier_tests/longformer_for_question_answering.py
  tests/nlu_core_tests/component_tests/span_classifier_tests/roberta_for_question_answering.py
  tests/nlu_core_tests/component_tests/span_classifier_tests/xlmroberta_for_question_answering.py
Labels: enhancement

#125 Feature/spark pipe to nlu pipe
  nlu/__init__.py
  nlu/pipe/col_substitution/col_name_substitution_utils.py
  nlu/pipe/col_substitution/col_substitution_HC.py
  nlu/pipe/col_substitution/col_substitution_OS.py
  nlu/pipe/col_substitution/substitution_map_HC.py
  nlu/pipe/component_resolution.py
  nlu/pipe/extractors/extractor_configs_HC.py
  nlu/pipe/extractors/extractor_configs_OS.py
  nlu/pipe/extractors/extractor_methods/helper_extractor_methods.py
  nlu/pipe/pipeline.py
  nlu/pipe/utils/output_level_resolution_utils.py
  nlu/pipe/utils/predict_helper.py
  nlu/pipe/viz/vis_utils.py
  nlu/pipe/viz/vis_utils_HC.py
  nlu/pipe/viz/vis_utils_OS.py
  nlu/universe/annotator_class_universe.py
  nlu/universe/component_universes.py
  nlu/universe/feature_node_ids.py
  nlu/universe/feature_node_universes.py
  nlu/universe/feature_universes.py
  nlu/universe/logic_universes.py
  tests/nlu_core_tests/partially_implemented_tests.py
  tests/nlu_hc_tests/component_tests/sentence_entity_resolver/sentence_entity_resolution_tests.py
Labels: bug, enhancement

#131 adding_images
  docs/assets/images/releases/4_0_0/en.map_entity.snomed_to_icd10cm.png
  docs/assets/images/releases/4_0_0/en.med_ner.pathogen.png
  docs/assets/images/releases/4_0_0/en.ner.clinical_trials_abstracts.png
  docs/assets/images/releases/4_0_0/es.med_ner.living_species.roberta.png
Labels: documentation

#132 FEATURE: add table extraction notebook
  examples/colab/ocr/table_extraction.ipynb
  tests/datasets/ocr/docx/tables.docx
  tests/datasets/ocr/images/tables.pdf
  tests/datasets/ocr/pdf/insurance.pdf
  tests/datasets/ocr/ppt/tables.ppt
Labels: notebooks

#133 Docs update and notebook fix
  docs/en/model_namespace.md
  docs/en/notebooks.md
  examples/colab/component_examples/classifiers/Question_vs_Statement.ipynb
  examples/colab/visualization/NLU_visualizations_tutorial.ipynb
Labels: documentation, notebooks
